### ISSUE TITLE
дублирование кода

### ISSUE THREAD

**Issue by dzhivushko** [BerserkDarkSol/G-JD1-2019-10-borisevich#10]
https://github.com/BerserkDarkSol/G-JD1-2019-10-borisevich/blob/6f068154b0c03e921c60e74cde7cba94a17b4b20/src/homework/practice2/TaskTwo.java#L187-L192

этот фрагмент повторяется несколько раз
очевидны метод printMatrix()

**Comment by BerserkDarkSol** [comment]
исправил
