### ISSUE TITLE
имена методов

### ISSUE THREAD

**Issue by dzhivushko** [BerserkDarkSol/G-JD1-2019-10-borisevich#11]
https://github.com/BerserkDarkSol/G-JD1-2019-10-borisevich/blob/6f068154b0c03e921c60e74cde7cba94a17b4b20/src/homework/practice2/TaskTwo.java#L32-L39

не должно быть никакого ing  в глаголах. это вроде называется "герундий" в английской грамматике. так вот он в именах методов не нужен. тут должен быть обычный глагол
finding->find и тп

**Comment by BerserkDarkSol** [comment]
изменил
