### ISSUE TITLE
пакеты пишутся с маленькой буквы

### ISSUE THREAD

**Issue by dzhivushko** [BerserkDarkSol/G-JD1-2019-10-borisevich#2]
оно не даст переименовать сразу, потому что на винде нет разницы между регистрами. потому можно переименовать сначала в classwork1. а потом уже просто classwork

![image](https://user-images.githubusercontent.com/12233334/67149761-00a18380-f2b8-11e9-836d-8c55ade8bae2.png)

**Comment by BerserkDarkSol** [comment]
изменил
