### ISSUE TITLE
повторяющийся текст

### ISSUE THREAD

**Issue by dzhivushko** [BerserkDarkSol/G-JD1-2019-10-borisevich#4]
"The number you have entered is equal to " - эта фраза повторяется 12 раз. если захочешь ее чуть исправить - надо будет сделать 12 раз.  потому просто вынести стринговую константу и написать 

String phrase="The number you have entered is equal to " ;
и дальше phrase+"January" и т.п.

или другой вариант - вынести метод,который принимает на вход только имя месяца и печатает всю фразу

https://github.com/BerserkDarkSol/G-JD1-2019-10-borisevich/blob/1c320cd63a7040f27a20b677f08a7a948a80377d/src/homework/practice1/taskOne.java#L12-L26

**Comment by BerserkDarkSol** [comment]
исправил
