### ISSUE TITLE
лишний объект

### ISSUE THREAD

**Issue by dzhivushko** [BerserkDarkSol/G-JD1-2019-10-borisevich#5]
Scanner - объект для работы с консолью. Но зачем их тут 2? скорее всего смысла в этом нет и все можно и нужно сделать одним.

https://github.com/BerserkDarkSol/G-JD1-2019-10-borisevich/blob/1c320cd63a7040f27a20b677f08a7a948a80377d/src/homework/practice1/taskTwo.java#L10-L12

**Comment by BerserkDarkSol** [comment]
удалил и изменил вызов inArray на in
