### ISSUE TITLE
бессмысленный метод

### ISSUE THREAD

**Issue by dzhivushko** [BerserkDarkSol/G-JD1-2019-10-borisevich#6]
что делает метод copyArray? копирует - я понимаю. А в чем смысл его вызывать и не воспользоваться возвращаемой переменной? думаю смысла тут нет и быть не может

https://github.com/BerserkDarkSol/G-JD1-2019-10-borisevich/blob/1c320cd63a7040f27a20b677f08a7a948a80377d/src/homework/practice1/taskTwo.java#L21-L40

**Comment by dzhivushko** [comment]
да и параметр надо называть НЕ copyArray, а напримери initialArray или просто array

**Comment by BerserkDarkSol** [comment]
удалил метод где он не используется
