### ISSUE TITLE
имена методов должны начинаться с глаголов

### ISSUE THREAD

**Issue by dzhivushko** [BerserkDarkSol/G-JD1-2019-10-borisevich#7]
первые два метода - ОК. Остальные - нет

https://github.com/BerserkDarkSol/G-JD1-2019-10-borisevich/blob/1c320cd63a7040f27a20b677f08a7a948a80377d/src/homework/practice1/taskTwo.java#L21-L28

**Comment by BerserkDarkSol** [comment]
changed it
