### ISSUE TITLE
имена переменных

### ISSUE THREAD

**Issue by dzhivushko** [BerserkDarkSol/G-JD1-2019-10-borisevich#9]
https://github.com/BerserkDarkSol/G-JD1-2019-10-borisevich/blob/6f068154b0c03e921c60e74cde7cba94a17b4b20/src/homework/practice2/TaskOne.java#L26-L31

старайся подбирать адекватные имена
тут например могли быть rows и cell

**Comment by BerserkDarkSol** [comment]
изменил
